org: yoacorgz
service: serverlessTemplateNode

provider:
  name: aws
  runtime: nodejs20.x
  architecture: arm64
  region: us-east-1
  iam:
    role:
      statements:
        - Effect: Allow
          Action: s3:PutObject
          Resource: arn:aws:s3:::awslambdatestbucketxd/*

package:
  individually: true

build:
  esbuild:
    bundle: true
    minify: true
    sourcemap: false
    exclude:
      - "@aws-sdk/*"

functions:
  upload:
    handler: src/upload.handler
    events:
      - httpApi:
          path: /upload
          method: POST
  users:
    handler: src/users.handler
    events:
      - httpApi:
          path: /users
          method: ANY
      - httpApi:
          path: /users/{param+}
          method: ANY
